name: Check-in tests

on:
  push:
    branches:
      - 'main'
      - 'releases-**'
  pull_request:
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:

  ci-ubuntu-server:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        db:
          - sqlite
          - mysql
          - mariadb
          - postgres

    steps:
    - name: Checkout
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

    - name: Set up Go
      uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d
      with:
        go-version-file: server/go.mod

    - name: "Test server: ${{matrix['db']}}"
      run: make server-test-${{matrix['db']}}

  ci-ubuntu-webapp:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      with:
        path: "focalboard"
        
    - name: npm ci
      run: cd focalboard/webapp && npm ci && cd -

    - name: Set up Go
      uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d
      with:
        go-version-file: focalboard/server/go.mod

    - name: Setup Node
      uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f
      with:
        node-version-file: focalboard/webapp/.nvmrc

    - name: Build Linux server
      run: cd focalboard; make server-linux-package

    - name: Copy server binary for Cypress
      run: cp focalboard/bin/linux/focalboard-server focalboard/bin/

    - name: Upload server package
      uses: actions/upload-artifact@2848b2cda0e5190984587ec6bb1f36730ca78d50
      with:
        name: focalboard-server-linux-amd64.tar.gz
        path: ${{ github.workspace }}/focalboard/dist/focalboard-server-linux-amd64.tar.gz

    - name: Lint & test webapp
      run: cd focalboard; make webapp-ci


