name: Production-Release

on: workflow_dispatch

env:
 EXCLUDE_ENTERPRISE: true
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:

  ubuntu:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        path: "focalboard"

    - name: Replace token 1 server
      run: sed -i -e "s,placeholder_rudder_dataplane_url,${{ secrets.RUDDER_DATAPLANE_URL }},g" ${{ github.workspace }}/focalboard/server/services/telemetry/telemetry.go

    - name: Replace token 2 server
      run: sed -i -e "s,placeholder_rudder_key,${{ secrets.RUDDER_PROD_KEY }},g" ${{ github.workspace }}/focalboard/server/services/telemetry/telemetry.go

    - name: npm ci
      run: cd focalboard/webapp; npm ci --no-optional

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version-file: focalboard/server/go.mod

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version-file: focalboard/webapp/.nvmrc

    - name: Build Linux server
      run: cd focalboard; make server-linux-package
      env:
        BUILD_NUMBER: ${{ github.run_id }}

    - name: Upload server package
      uses: actions/upload-artifact@2848b2cda0e5190984587ec6bb1f36730ca78d50
      with:
        name: focalboard-server-linux-amd64.tar.gz
        path: ${{ github.workspace }}/focalboard/dist/focalboard-server-linux-amd64.tar.gz


